# my-mongo-deployment.yaml
# apiVersion: apps/v1
# # kind: Deployment
# kind: Pod
apiVersion: v1
kind: Pod
metadata:
  name: my-mongo
spec:
  # selector:
  #   matchLabels:
  #     app: my-mongo
  #     environment: my
  # replicas: 1
  # strategy:
  #   type: Recreate
  # template:
  #   metadata:
  #     labels:
  #       app: my-mongo
  #       environment: my
    # spec:
      hostname: my-mongo
      runtimeClassName: quark
      volumes:
        - name: my-mongo-persistent-storage
          persistentVolumeClaim:
            claimName: my-mongo-pvc
        - name: my-mongo-config
          configMap:
            name: my-mongo-config
        - name: my-mongo-ssl-certs
          secret:
            secretName: my-mongo-ssl-certs
      containers:
        - name: my-mongo
          image: mongo:3.6
          #args: ["--auth"] # this flag will enable authentication
          args:
            - --config
            - /etc/mongo/mongod.conf
          # imagePullPolicy: Always
          # ports:
          #   - containerPort: 27017
          volumeMounts:
            - name: my-mongo-persistent-storage
              mountPath: /data/db
            - name: my-mongo-config
              mountPath: /etc/mongo
            - name: my-mongo-ssl-certs
              mountPath: /etc/ssl


